export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_USERS_MENU = 'REQUEST_USERS_MENU';
export const RECEIVE_USERS_MENU = 'RECEIVE_USERS_MENU';